const STATES_LIST = [
  { text: 'AC' },
  { text: 'AL' },
  { text: 'AP' },
  { text: 'AM' },
  { text: 'BA' },
  { text: 'CE' },
  { text: 'DF' },
  { text: 'ES' },
  { text: 'GO' },
  { text: 'MA' },
  { text: 'MT' },
  { text: 'MS' },
  { text: 'MG' },
  { text: 'PA' },
  { text: 'PB' },
  { text: 'PR' },
  { text: 'PE' },
  { text: 'PI' },
  { text: 'RJ' },
  { text: 'RN' },
  { text: 'RS' },
  { text: 'RO' },
  { text: 'RR' },
  { text: 'SC' },
  { text: 'SP' },
  { text: 'SE' },
  { text: 'TO' },
];

export default STATES_LIST;
